[versions]
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
composeHotReload = "1.0.0"
composeMultiplatform = "1.9.3"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
detekt = "1.23.8"

nav3ui = "1.1.0-alpha01"
#nav3materialAdaptive = "1.3.0-alpha03"
nav3lifeCycleViewModel = "2.10.0-alpha07"

arrow = "2.2.1.1"
kotest = "6.0.7"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
koin = "4.2.0-beta2"
koin-annotations = "2.3.2-Beta1"
klogging = "0.11.7"
ksp = "2.3.4"
composeUnstyled = "1.49.5"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

androidx-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "nav3ui" }
androidx-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "nav3lifeCycleViewModel" }
#androidx-material3-adaptive-navigation3 = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "nav3materialAdaptive" }

kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }


arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-core-serialization = { module= "io.arrow-kt:arrow-core-serialization", version.ref = "arrow"}
arrow-fxCoroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
arrow-optics-compose = { module = "io.arrow-kt:arrow-optics-compose", version.ref = "arrow" }
arrow-optics-ksp = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-arrow = { module = "io.kotest:kotest-assertions-arrow", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-property-arrow = { module = "io.kotest:kotest-property-arrow", version.ref = "kotest" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose-viewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-navigation3 = { module = "io.insert-koin:koin-compose-navigation3", version.ref = "koin"}
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

klogging = { module = "io.klogging:klogging", version.ref = "klogging" }

kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
mediaPlayer = { module = "org.openani.mediamp:mediamp-all", version = "0.0.30" }

unstyled = { module = "com.composables:composeunstyled", version.ref = "composeUnstyled"}
unstyled-theming = { module = "com.composables:composeunstyled-theming", version.ref = "composeUnstyled"}
unstyled-primitives = { module = "com.composables:composeunstyled-primitives", version.ref = "composeUnstyled"}
unstyled-platformTheme = { module = "com.composables:composeunstyled-platformtheme", version.ref = "composeUnstyled"}


[bundles]
unstyled = ["unstyled", "unstyled-theming", "unstyled-primitives", "unstyled-platformTheme"]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
arrow  = ["arrow-core", "arrow-fxCoroutines", "arrow-resilience", "arrow-optics","arrow-optics-compose","arrow-core-serialization"]
kotest = ["kotest-assertions-core", "kotest-assertions-arrow", "kotest-property", "kotest-property-arrow"]
koin = ["koin-core", "koin-compose-viewModel", "koin-annotations","koin-navigation3"]
androidx-multiplatform = [
    "androidx-lifecycle-runtimeCompose",
    "androidx-lifecycle-viewmodelCompose",
    "androidx-navigation3-ui",
    "androidx-lifecycle-viewmodel-navigation3",
#    "androidx-material3-adaptive-navigation3",
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotest = { id = "io.kotest", version.ref = "kotest"}
vlcSetup = { id = "ir.mahozad.vlc-setup", version = "0.1.0"}
detekt = {id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
