naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
  MatchingDeclarationName:
    ignoreAnnotated:
      - KoinViewModel
style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - Preview
  ForbiddenImport:
    active: true
    severity: error
    forbiddenPatterns: 'androidx\.compose\.material3\..*'
complexity:
  TooManyFunctions:
    ignoreAnnotated:
      - Preview

